services:
  - type: web
    name: corelara-api
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
    startCommand: gunicorn coreLaraServer.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: corelara-api.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: corelara-db
          property: connectionString
      - key: DB_NAME
        fromDatabase:
          name: corelara-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: corelara-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: corelara-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: corelara-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: corelara-db
          property: port

databases:
  - name: corelara-db
    plan: free
