services:
  - type: web
    name: corelara-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn coreLaraServer.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: corelara-api.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: corelara-db
          property: connectionString

databases:
  - name: corelara-db
    plan: free
