name: Deploy Render

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-main
  cancel-in-progress: false

jobs:
  deploy:
    name: Trigger Render deploy
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && success()

    steps:
      - name: Trigger Render Deploy Hook
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          if [ -z "$RENDER_DEPLOY_HOOK" ]; then
            echo "RENDER_DEPLOY_HOOK secret not set!" >&2
            exit 1
          fi
          curl -fsSL -X POST "$RENDER_DEPLOY_HOOK"
          echo "Deploy triggered."
